//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Organization.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tbl_Gallaries
    {
        public int Gid { get; set; }

        [Required(ErrorMessage = "Title is required*")]
        [Display(Name = "Title")]
        public string GallaryTitle { get; set; }
        public string GallaryImage { get; set; }
        public int AdminID { get; set; }

        public Nullable<int> ImageStatus { get; set; }

        [Required(ErrorMessage = "Image is a required field*")]
        [Display(Name = "Choose Image")]
        public HttpPostedFileBase GalleryImgFile { get; set; }
        public virtual tbl_Admins tbl_Admins { get; set; }
    }
}


