//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Organization.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_TeamMemberTitles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TeamMemberTitles()
        {
            this.tbl_TeamMembers = new HashSet<tbl_TeamMembers>();
        }

        public int TitleID { get; set; }

        [Required(ErrorMessage = "Title Name is required*")]
        [Display(Name = "Title Name")]
        public string TitleName { get; set; }

        [Required(ErrorMessage = "Admin ID is required*")]
        [Display(Name = "Admin")]
        public int AdminID { get; set; }

        public virtual tbl_Admins tbl_Admins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TeamMembers> tbl_TeamMembers { get; set; }
    }
}
