//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Organization.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Volunteers
    {
        public int VolunteerID { get; set; }

        [Required(ErrorMessage = "Name is required*")]
        [Display(Name = "Name")]
        public string VolunteerName { get; set; }

        [Required(ErrorMessage = " Let us know why you want to be a volunteer*")]
        [Display(Name = "Reason")]
        public string VolunteerReason { get; set; }


        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Please enter Valid Email*")]
        [Required(ErrorMessage = "Email is required*")]
        [Display(Name = "Email")]
        public string VolunteerEmail { get; set; }

        [Required(ErrorMessage = "volunteer types is required *")]
        [Display(Name = "Select Type")]
        public int VolunteerTypeID { get; set; }

        public virtual tbl_VolunteerTypes tbl_VolunteerTypes { get; set; }
    }
}

