//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Organization.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tbl_Achivements
    {
        public int AchiveID { get; set; }

        [Required(ErrorMessage = "Title Field is required*")]
        [Display(Name = "Title")]
        public string AchiveTitle { get; set; }


        public string AchiveImage { get; set; }

        [Required(ErrorMessage = "Description Field is required*")]
        [Display(Name = "Description")]
        public string AchiveDescription { get; set; }

        [Required(ErrorMessage = "DateTime Field is required*")]
        [Display(Name = "Date And Time")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        public System.DateTime AchiveDateTime { get; set; }


        [Required(ErrorMessage = "Admin ID Field is required*")]
        [Display(Name = "Admin ID")]
        public int AdminID { get; set; }

        public Nullable<int> AchiveStatus { get; set; }


        [Required(ErrorMessage = "Image Field is required*")]
        [Display(Name = "Choose Image")]
        public HttpPostedFileBase AchivementImgFile { get; set; }

        public virtual tbl_Admins tbl_Admins { get; set; }
    }
}

