//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Organization.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_VolunteerTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_VolunteerTypes()
        {
            this.tbl_Volunteers = new HashSet<tbl_Volunteers>();
        }

        [Required(ErrorMessage = "volunteer types is required *")]
        [Display(Name = "Select Type")]
        public int VolunteerTypeID { get; set; }

        [Required(ErrorMessage = "Title name is required*")]
        [Display(Name = "Name")]
        public string VolunteerTypeName { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Volunteers> tbl_Volunteers { get; set; }
    }
}