//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Organization.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tbl_Admins
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Admins()
        {
            this.tbl_aboutus = new HashSet<tbl_aboutus>();
            this.tbl_Achivements = new HashSet<tbl_Achivements>();
            this.tbl_AssociativeNGO = new HashSet<tbl_AssociativeNGO>();
            this.tbl_Blogs = new HashSet<tbl_Blogs>();
            this.tbl_DonationCauses = new HashSet<tbl_DonationCauses>();
            this.tbl_Events = new HashSet<tbl_Events>();
            this.tbl_Gallaries = new HashSet<tbl_Gallaries>();
            this.tbl_Projects = new HashSet<tbl_Projects>();
            this.tbl_TeamMemberTitles = new HashSet<tbl_TeamMemberTitles>();
            this.tbl_TeamMembers = new HashSet<tbl_TeamMembers>();
        }

        public int AdminID { get; set; }
        public string AdminFirstName { get; set; }
        public string AdminLastName { get; set; }

        [Required(ErrorMessage = "Username is required*")]
        [Display(Name = "Username")]
        public string AdminUsername { get; set; }
        public string AdminEmail { get; set; }

        [Required(ErrorMessage = "Password is required*")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string AdminPassword { get; set; }

        public bool RememberMe { get; set; }
        public string AdminImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_aboutus> tbl_aboutus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Achivements> tbl_Achivements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AssociativeNGO> tbl_AssociativeNGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Blogs> tbl_Blogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DonationCauses> tbl_DonationCauses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Events> tbl_Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Gallaries> tbl_Gallaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Projects> tbl_Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TeamMemberTitles> tbl_TeamMemberTitles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TeamMembers> tbl_TeamMembers { get; set; }
    }
}
