//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Organization.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_aboutus
    {


        public int AboutID { get; set; }

        [Required(ErrorMessage = "What we do Field is required*")]
        [Display(Name = "What We D0")]
        public string WhatWeDo { get; set; }

        [Required(ErrorMessage = "Career With Us Field is required*")]
        [Display(Name = "Career With Us")]
        public string CareerWithUs { get; set; }

        [Required(ErrorMessage = "Read About Us Field is required*")]
        [Display(Name = "Read About Us")]
        public string ReadAboutUS { get; set; }

        [Required(ErrorMessage = "Our Mission Field is required*")]
        [Display(Name = "Our Mission")]
        public string OurMission { get; set; }

        [Required(ErrorMessage = "Admin ID Field is required*")]
        [Display(Name = "Admin ID")]
        public Nullable<int> AdminID { get; set; }

        public virtual tbl_Admins tbl_Admins { get; set; }
    }
}
