//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Organization.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    public partial class tbl_contactus
    {
        public int ContactID { get; set; }

        [Required(ErrorMessage = "Name is required*")]
        [Display(Name = "Name")]
        public string ContactName { get; set; }

        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Please enter Valid Email*")]
        [Required(ErrorMessage = "Email is required*")]
        [Display(Name = "Email")]
        public string ContactEmail { get; set; }

        [Required(ErrorMessage = "subject is required*")]
        [Display(Name = "Subject")]
        public string ContactSubject { get; set; }

        [Required(ErrorMessage = "Message is required*")]
        [Display(Name = "Message")]
        public string ContactMessage { get; set; }

        public Nullable<int> UserID { get; set; }

        public virtual tbl_Users tbl_Users { get; set; }
    }
}
