//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Organization.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tbl_Blogs
    {
        public int BlogID { get; set; }

        [Required(ErrorMessage = "Title is required*")]
        [Display(Name = "Title")]
        public string BlogTitle { get; set; }


        public string BlogImage { get; set; }

        [Required(ErrorMessage = "Description is required*")]
        [Display(Name = "Description")]
        public string BlogDescription { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        [Required(ErrorMessage = "Date is required*")]
        public System.DateTime BlogDateTime { get; set; }
        public int AdminID { get; set; }


        public Nullable<int> BlogStatus { get; set; }

        [Required(ErrorMessage = "Image is required*")]
        [Display(Name = "Choose Image")]
        public HttpPostedFileBase BlogImgFile { get; set; }
        public virtual tbl_Admins tbl_Admins { get; set; }
    }
}

