//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Organization.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tbl_Projects
    {
        public int ProjectID { get; set; }

        [Required(ErrorMessage = "Title is required*")]
        [Display(Name = "Title")]
        public string ProjectTitle { get; set; }

        [Required(ErrorMessage = "Description is required*")]
        [Display(Name = "Description")]
        public string ProjectDescription { get; set; }
        public string ProjectImage { get; set; }

        [Required(ErrorMessage = "Date and Time is required*")]
        [Display(Name = "Date and Time")]
        public System.DateTime ProjectDateTime { get; set; }

        [Required(ErrorMessage = "Member name is required*")]
        [Display(Name = "Incharge")]
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> AdminID { get; set; }


        [Required(ErrorMessage = "Image is required*")]
        [Display(Name = "Choose Image")]
        public HttpPostedFileBase ProjectImgFIle { get; set; }

        public Nullable<int> ProjectStatus { get; set; }

        public virtual tbl_Admins tbl_Admins { get; set; }
        public virtual tbl_TeamMembers tbl_TeamMembers { get; set; }
    }
}

